trigger: 
 - main

variables:
 - group: component-test-vg

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  displayName: "Install Go tooling"
  inputs:
    version: '1.13.5'


- task: TerraformInstaller@0
  displayName: "Install Terraform tooling"
  inputs:
    terraformVersion: '0.12.3'



# - task: AzureCLI@2
#   displayName: Azure CLI
#   inputs:
#     azureSubscription: $(AZCONNECTION)
#     scriptType: pscore
#     scriptLocation: inlineScript
#     inlineScript: |
#       az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)

- bash: |
    curl --location --silent --fail --show-error -o terratest_log_parser https://github.com/gruntwork-io/terratest/releases/download/v0.13.13/terratest_log_parser_linux_amd64
    chmod +x terratest_log_parser
    sudo mv terratest_log_parser /usr/local/bin
    az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
    cd test
    go mod init necdemo
    go test -v | tee test_output.log
    terratest_log_parser -testlog test_output.log -outputdir test_output
    ls /home/vsts/work/1/s/test/test_output
    ls /home/vsts/work/1/s/test/test_output/TestSimpleTerraform
  displayName: "Run the tests"  

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '/home/vsts/work/1/s/test/test_output/report.xml'
    failTaskOnFailedTests: true