trigger: 
 - main

variables:
 - group: component-test-vg

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  displayName: "Install Go tooling"
  inputs:
    version: '1.13.5'


- task: TerraformInstaller@0
  displayName: "Install Terraform tooling"
  inputs:
    terraformVersion: '0.12.3'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: $(AZCONNECTION)
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)

- bash: |
    cd test
    go mod init necdemo
    go test -v
  displayName: "Run the tests"  